name: Bun & Deno

on:
  - push
  - pull_request
jobs:
  deno:
    name: Deno
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
      - uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755 # v2.0.2
      - run: deno install
      - run: deno run build
      - run: deno --allow-env --allow-write --allow-read index.test.js
  bun:
    name: Bun CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
      - run: bun install
      - run: bun run build
      - run: bun index.test.js
