name: Run tests
on:
  - push
  - pull_request
jobs:
  test-js:
    name: 'jsbt v0.3.3' # Should match commit below
    uses: paulmillr/jsbt/.github/workflows/test-js.yml@c9a9f2cd6b4841aa3117b174e9ea468b1650e5ea
